const {
  SPOTIFYWRAP_DB_USER = "",
  SPOTIFYWRAP_DB_PASSWORD = "",
  SPOTIFYWRAP_DB_URI = "",
  SPOTIFYWRAP_DB_NAME = "",
  SPOTIFYWRAP_DB_COLLECTION = "",
  SPOTIFYWRAP_API_USER = "",
  SPOTIFYWRAP_API_PASSWORD = "",
  SPOTIFYWRAP_SPOTIFY_CLIENT_ID = "",
  SPOTIFYWRAP_SPOTIFY_CLIENT_SECRET = "",
  SPORTIFYWRAP_APP_PORT = 3000,
} = process.env;

module.exports = {
  SPOTIFYWRAP_DB_USER,
  SPOTIFYWRAP_DB_PASSWORD,
  SPOTIFYWRAP_DB_URI,
  SPOTIFYWRAP_DB_NAME,
  SPOTIFYWRAP_DB_COLLECTION,
  SPOTIFYWRAP_API_USER,
  SPOTIFYWRAP_API_PASSWORD,
  SPOTIFYWRAP_SPOTIFY_CLIENT_ID,
  SPOTIFYWRAP_SPOTIFY_CLIENT_SECRET,
  SPORTIFYWRAP_APP_PORT,
};
